[package]
name = "memory-serve-test"
edition = "2024"

[dependencies]
memory-serve = { path = "../" }
axum = "0.8"
tokio = { version = "1.0", features = ["full"] }
tracing-subscriber = "0.3"
tracing = "0.1"

[build-dependencies]
memory-serve = { path = "../" }
